name:  Test, build and deploy
on: [push,pull_request]
jobs:
  build_deploy:
  
    if: github.event_name != 'pull_request'
    runs-on: macos-latest
  
    name: Build  apk  and web
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: 'stable'
    
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
    
      - run: flutter build apk --debug --split-per-abi
    
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}